import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Botbar from "@/components/global/BottomBar";
import Navbar from "@/components/global/Nav";
import ReduxProvider from "@/components/ReduxProvider";
// import { CartProvider } from "@/contexts/CartContext";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ReduxProvider>
            {/* <CartProvider> */}
            <Navbar />
            <div className="my-20 h-full w-full">{children}</div>
            <Toaster />
            <Botbar />
            {/* </CartProvider> */}
          </ReduxProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
